# Generated by Django 5.1.4 on 2025-12-07 15:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('country', 'name'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль (хэш)')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='WeatherIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Код / название иконки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weather_icons/', verbose_name='Файл иконки')),
                ('image_url', models.URLField(blank=True, verbose_name='URL иконки')),
            ],
            options={
                'verbose_name': 'Иконка погоды',
                'verbose_name_plural': 'Иконки погоды',
            },
        ),
        migrations.CreateModel(
            name='MoonAndPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_phase', models.CharField(max_length=50, verbose_name='Фаза Луны')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительные параметры')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meteo.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Луна и фазы',
                'verbose_name_plural': 'Луна и фазы',
            },
        ),
        migrations.CreateModel(
            name='SunAndVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunrise', models.TimeField(verbose_name='Время восхода')),
                ('sunset', models.TimeField(verbose_name='Время заката')),
                ('road_visibility', models.FloatField(blank=True, null=True, verbose_name='Видимость на дорогах (км)')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meteo.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Солнце и видимость',
                'verbose_name_plural': 'Солнце и видимость',
            },
        ),
        migrations.CreateModel(
            name='SelectedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.city', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meteo.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выбранный город',
                'verbose_name_plural': 'Выбранные города',
            },
        ),
        migrations.CreateModel(
            name='AtmosphericData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('precipitation', models.FloatField(default=0.0, verbose_name='Осадки (мм)')),
                ('wind_gusts', models.FloatField(blank=True, null=True, verbose_name='Порывы ветра (м/с)')),
                ('uv_index', models.FloatField(blank=True, null=True, verbose_name='УФ-индекс')),
                ('humidity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Влажность (%)')),
                ('dew_point', models.FloatField(blank=True, null=True, verbose_name='Точка росы (°C)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Давление (гПа)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Атмосферные показатели',
                'verbose_name_plural': 'Атмосферные показатели',
                'ordering': ('city', 'date'),
                'indexes': [models.Index(fields=['city', 'date'], name='meteo_atmos_city_id_8303cb_idx')],
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ViewedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.city', verbose_name='Город')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотренный город',
                'verbose_name_plural': 'Просмотренные города',
                'indexes': [models.Index(fields=['user', 'city'], name='meteo_viewe_user_id_af2e60_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('fact', models.BooleanField(verbose_name='Факт погоды (Да/Нет)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время подтверждения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.city', verbose_name='Город')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подтверждение погоды',
                'verbose_name_plural': 'Подтверждения погоды',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время прогноза')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('feels_like', models.FloatField(blank=True, null=True, verbose_name='Ощущается как (°C)')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='Состояние (текст)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.city', verbose_name='Город')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meteo.weathericon', verbose_name='Иконка погоды')),
            ],
            options={
                'verbose_name': 'Почасовой прогноз',
                'verbose_name_plural': 'Почасовые прогнозы',
                'ordering': ('city', 'datetime'),
                'indexes': [models.Index(fields=['city', 'datetime'], name='meteo_hourl_city_id_e81cb2_idx')],
            },
        ),
    ]
